import{a as b,i as n,S as w}from"./assets/vendor-c493984e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();function g(o){return o.map(({webformatURL:r,largeImageURL:a,tags:i,likes:e,views:t,comments:s,downloads:L})=>`
        <a href="${a}" target="_blank" rel="noopener noreferrer">
          <li class="item">
            <img src="${r}" alt="${i}" width="360" height="170">
            <div class="statistic">
              <p>Likes:<br> <span>${e}</span></p>
              <p>Views:<br> <span>${t}</span></p>
              <p>Comments:<br> <span>${s}</span></p>
              <p>Downloads:<br> <span>${L}</span></p>
            </div>
          </li>
        </a>
      `).join("")}async function h(o,r){const e="https://pixabay.com/api/",t={params:new URLSearchParams({key:"44403468-b3192a3f07a9f4ae6c998e95a",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15})};try{return(await b.get(e,t)).data}catch(s){throw n.error({title:"Error",message:"Please enter a search term",position:"topRight"}),s}}const m=document.querySelector(".form"),f=document.querySelector(".nav-list"),p=document.querySelector(".loader"),d=document.querySelector(".loadbtn-js");let u=1,l,c;m.addEventListener("submit",async o=>{if(o.preventDefault(),u=1,l=o.target.elements.search.value.trim(),!l){n.error({title:"Error",message:"Please enter a search term",position:"topRight"});return}p.style.display="block";try{const r=await h(l,u);if(r.hits.length===0){n.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),y();return}const a=g(r.hits);f.innerHTML=a,E(),c?c.refresh():c=new w(".gallery a"),m.reset()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p.style.display="none"}});function E(){d.classList.remove("hidden")}function y(){d.classList.add("hidden")}d.addEventListener("click",async()=>{u++,p.style.display="block";try{const o=await h(l,u);if(o.hits.length===0){n.warning({title:"No more results",message:"Sorry, there are no more images matching your search query.",position:"topRight"}),y();return}const r=g(o.hits);f.insertAdjacentHTML("beforeend",r),c.refresh()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
