import{a as L,i,S as w}from"./assets/vendor-c493984e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function g(o){return o.map(({webformatURL:r,largeImageURL:n,tags:a,likes:e,views:t,comments:s,downloads:E})=>`
        <a href="${n}" target="_blank" rel="noopener noreferrer">
          <li class="item">
            <img src="${r}" alt="${a}" width="360" height="170">
            <div class="statistic">
              <p>Likes:<br> <span>${e}</span></p>
              <p>Views:<br> <span>${t}</span></p>
              <p>Comments:<br> <span>${s}</span></p>
              <p>Downloads:<br> <span>${E}</span></p>
            </div>
          </li>
        </a>
      `).join("")}async function f(o,r){const e="https://pixabay.com/api/",t={params:new URLSearchParams({key:"44403468-b3192a3f07a9f4ae6c998e95a",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15})};try{return(await L.get(e,t)).data}catch(s){throw i.error({title:"Error",message:"Please enter a search term",position:"topRight"}),s}}const m=document.querySelector(".form"),u=document.querySelector(".nav-list"),p=document.querySelector(".loader"),h=document.querySelector(".loadbtn-js");let d=1,l,c;m.addEventListener("submit",async o=>{if(o.preventDefault(),d=1,b(),l=o.target.elements.search.value.trim(),!l){i.error({title:"Error",message:"Please enter a search term",position:"topRight"});return}p.style.display="block";try{const r=await f(l,d);if(r.hits.length===0){i.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const n=g(r.hits);u.innerHTML=n,y(),c?c.refresh():c=new w(".gallery a"),m.reset()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p.style.display="none"}});h.addEventListener("click",async()=>{d++,b(),p.style.display="block";try{const o=await f(l,d);if(o.hits.length===0){i.info({title:"The End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}const r=g(o.hits);u.insertAdjacentHTML("beforeend",r),c.refresh(),v(),y()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p.style.display="none"}});function y(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}function v(){const o=u.children[0];if(o){const r=o.getBoundingClientRect().height;scrollBy({top:r*4,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
